language: ruby
rvm:
 - 2.6
 - 2.7

services:
 - redis-server
 - postgresql


addons:

  chrome: stable

  apt:

    sources:

      - sourceline: "ppa:mc3man/trusty-media"

      - sourceline: "ppa:ubuntuhandbook1/apps"

    packages:

      - ffmpeg

      - mupdf

      - mupdf-tools

      - poppler-utils


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/storage.yml.travis config/storage.yml
  - bundle exec rails db:test:prepare

before_install:

  - "rm ${BUNDLE_GEMFILE}.lock"

  - "travis_retry gem update --system"

  - "travis_retry gem install bundler"

cache:
  - bundler


